### PR TITLE
Adding fuzzinozer.py (as intents.fuzzinozer module)

### PR DESCRIPTION
**Pull request by stefania26**
Please review my module.
It should be put within an intents folder (having an __init__.py file inside, such that it will be called from drozer as "run intents.fuzzinozer")

### CODE REVIEW

**Comment by HenryHoggard** [comment]
Hi Stefania,

Sorry to keep pushing back. Can you please re submit this inside a sub folder rather than to the root directory.

The folder name can be your name, company or handle. For example

`stefania26/fuzzinozer.py`

Thanks

**Comment by stefania26** [comment]
Hi,
I have tried to add the fuzzinozer module under a subfolder inside the drozer-modules repo using git and i got the following error:
remote: Permission to mwrlabs/drozer-modules.git denied to stefania26.
fatal: unable to access 'https://github.com/mwrlabs/drozer-modules.git/': The requested URL returned error: 403
Regards,Stefania



    On Thursday, February 4, 2016 11:42 AM, Henry <notifications@github.com> wrote:
 

 Closed #4.—

**Comment by HenryHoggard** [comment]
It looks like you tried to push directly to this repository, you will need to fork this repository, make the changes on your own repository, then create a new pull request.

Thanks

**Comment by stefania26** [comment]
I have managed to add the module now. I have also create a new pull request.
Thanks,Stefania 

    On Friday, February 5, 2016 12:11 PM, Henry <notifications@github.com> wrote:
 

 It looks like you tried to push directly to this repository, you will need to fork this repository, make the changes on your own repository, then create a new pull request.Thanks—

**Pull request closed without merging**
